# Server Configuration
server.port=8083

# Application Name
spring.application.name=product

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/product
spring.data.mongodb.database=product

# Logging Configuration
logging.level.com.marketplace.product=INFO
logging.level.org.springframework.web=INFO

